### ISSUE TITLE
[Proposal] Fire input event after updating the hidden field

### ISSUE THREAD

**Issue by vespakoen** [uploadcare/uploadcare-widget#150]
Hey guys,

I am using angularjs, when using the simple input syntax, and bind the value to my scope / model, it does not get updated when the value is changed by uploadcare.

To solve this, an "input" event should be triggered by the uploadcare-widget.

``` js
jQueryReferenceToTheInput.trigger('input');
```

For now, I am trying to work around this by attaching a listener to the widgets, but getting the widgets seems pretty hard too with angularjs.

Will update this issue with my workaround once I have it working..

**Comment by nd0ut** [comment]
We have [angular-uploadcare](https://github.com/uploadcare/angular-uploadcare) и [ngx-uploadcare-widget](https://github.com/uploadcare/ngx-uploadcare-widget) so I close the issue.
