### ISSUE TITLE
Cropping doesn't always appear in widget after upload

### ISSUE THREAD

**Issue by hsubu** [uploadcare/uploadcare-widget#177]
The cropping widget creates frequent buggy behavior when I'm trying to use it.  

I'm using the "data-crop" attribute on my upload input, and most of the time it works fine, but about 10% of the time the images loads in the preview and the crop selector never appears.  It seems that the startCrop() function doesn't even trigger, because the "Done" button remains disabled.  So, the photo is showing in preview, but the user can't crop or click "Done".  It requires exiting and re-uploading.

My current workaround is to delay the startCrop() action by 500ms.  To do this, I updated the utils.defer method:

    ns.defer = function(fn, delay) {
        return setTimeout(fn, delay || 0);
    };

and

    return imgLoader.done(function() {
        return utils.defer(startCrop, 500);
    });

Of course, this is only a workaround, so I'll monitor it for effectiveness.  Any ideas on what might be causing this?

My stack includes angularjs and no native jQuery, if that makes any difference.

Thank you!

**Comment by homm** [comment]
Sorry, not confirmed by tests and other clients.
