### ISSUE TITLE
Set AUTOSTORE by default

### ISSUE THREAD

**Issue by homm** [uploadcare/uploadcare-widget#199]
Most of users do not expect what uploaded files are disappear in one day after uploading. But we can't turn it on in one of our minor versions (1.6, 1.7), because no one use `AUTOSTORE = false` right now.

We can make AUTOSTORE mandatory settings from next minor version (1.6) and set it by default in next major version (2.0).

**Comment by dmitry-mukhin** [comment]
make it happen already!

**Comment by homm** [comment]
see #205
