### ISSUE TITLE
[Request] Include release in github repo

### ISSUE THREAD

**Issue by vespakoen** [uploadcare/uploadcare-widget#203]
And publish on npm.

This makes integrating it in CommonJS applications a lot easier.

**Comment by homm** [comment]
We already have a repo with releases for Bower. https://github.com/uploadcare/uploadcare-bower
Also there is a package with some useful function on npm https://www.npmjs.com/package/uploadcare
Do you want to see widget on npm?

**Comment by vespakoen** [comment]
Exactly, I would like to be able to host the widget myself, basically the bower sources but then on npm.
A lot of people use "npm for everything" and up until now, this is the only project I cannot grab from npm, which is a missed chance imo.

**Comment by vespakoen** [comment]
The bower repo is nice, but unfortunately it doesn't contain a package.json.
Because of that it cannot be installed through npm (not even with the git url).

I added a package.json to the uploadcare-bower package myself and published it on npm under "uploadcare-widget-npm", the -npm postfix is so it will not collide with (hopefully) your future uploads.

**Comment by dmitry-mukhin** [comment]
Not sure what you're talking about. Why don't send a PR to uploadcare-bower and don't multiply packages?

**Comment by vespakoen** [comment]
See my issue over at uploadcare-bower, hope it helps.

**Comment by nd0ut** [comment]
I'll close it as widget can be installed through NPM today.
