### ISSUE TITLE
amazon s3

### ISSUE THREAD

**Issue by arsenslyusarchuk** [uploadcare/uploadcare-widget#210]
Hello. I'm using your javascript widget with Rails on the backend side. 
As I understood, widget uploads files to CDN always. After that I have to take that link and make my own API call to save it to s3. Am I missing smth? I thought it should upload to s3 automatically and then I can just store that link in my database

**Comment by dmitry-mukhin** [comment]
You're not missing anything. At the moment you have to issue explicit requests to copy file to your S# bucket.
We're working on autocopy, but I cannot give you any estimations at the moment.

**Comment by arsenslyusarchuk** [comment]
But that sucks. I thought when I bought this plugin I would not care about that. So what is the reason then to connect S3 in profile?
Plus, when talking about multi upload, u have such word as 'group' of files. And I think when I decided to change files in particular group (I mean group remains the same but some files are new and some files are going to be deleted) u are not deleting the old files - u're just uploading new ones.

**Comment by arsenslyusarchuk** [comment]
So right now I don't see a reason to buy uploadcare. Sounds like just the waste of money. 
Also, removing the files on UI (from popup and then clicking 'done' button, or 'remove all' button when this is multi upload) should make call to chosen storage automatically.

**Comment by dmitry-mukhin** [comment]
Sorry to hear that.
The reason to connect S3 bucket to profile is to be able to copy files there. As I have said earlier, at the moment this calls for extra API request.

Group cannot be changed.
When you reorder, remove or add files in a group, you create a new one. Please read [this](https://uploadcare.com/documentation/javascript_api/#file-group) to get better understanding of how groups work.

**Comment by dmitry-mukhin** [comment]
@arsenslyusarchuk,
if you want a refund, please contact help@uploadcare.com.
Our service is not for everyone and we're sorry if you were mislead.

**Comment by arsenslyusarchuk** [comment]
Ok, lets forgot about s3. If I bought uploadcare, should I always make separate API request to store them, or UPLOADCARE_STORE flag in javascript plugin settings is enough? If so, should I care about some storage size limitations? (because I have to upload videos too)

**Comment by arsenslyusarchuk** [comment]
Ahh, I see that UPLOADCARE_STORE can be enabled in project settings.

**Comment by homm** [comment]
UPLOADCARE_STORE is the flag for the Upload API, if you don't work with Upload API directly, you don't need it.

As you mentioned, autostore can be enabled in project settings. All stored files are kept permanently until you explicitly remove them through REST API.

The storage size depends on plan. When you reach limits, you can switch to next plan or pay for over usage. All prices on this page: https://uploadcare.com/pricing/
