### ISSUE TITLE
Copying to Amazon

### ISSUE THREAD

**Issue by arsenslyusarchuk** [uploadcare/uploadcare-widget#211]
Hello. I've connected amazon S3 account through my profile on your website. As I know, to store my files on S3 I should manually copy them after I got temporary CDN link and I can use your API for that (I'm doing it through background job because upload to S3 takes much more time than to CDN). 
Also, I don't want to store these files on your default CDN, because I have videos also and I can go out of limit which I don't want to pay for. 
That's why I decided to switch-off an "autostore" property. 
So, initially my file is served from CDN but as soon as upload to S3 is complete I want to serve it from there.
My question is: what should I save to my database(uuid of file, link, etc) to be sure that uploadcare widget can serve those files automatically from S3 after file is automatically deleted from CDN?

**Comment by dmitry-mukhin** [comment]
Arsen,

this is not widget's job to show files.
If you do not want to use our storage, you shouldn't use our CDN.

After copying a file, you get an S3 object link, and work with it.

**Comment by arsenslyusarchuk** [comment]
WAT? It is said that I can pass uuid or CDN link when I initialize your JS widget to show those files. Can I pass S3 link to do the same thing? If not, how then I can perform some operations on uploaded files which are stored on S3 through your widget?

**Comment by dmitry-mukhin** [comment]
Widget's job is uploading files. It is possible to set it's value to a file that is already in Uploadcare storage, but this is just a helper and was never meant as a way to distribute files back to your users.
If you're doing this, this is not supported behavior and you're on your own.

Why don't you contact us directly so we can suggest a better way of using Uploadcare? GitHub issues is really not a good place for these conversations.
