### ISSUE TITLE
Reset back button

### ISSUE THREAD

**Issue by michaellouieloria** [uploadcare/uploadcare-widget#213]
Is there a way to reset?

![file counter](https://cloud.githubusercontent.com/assets/1403647/6666384/d7a9b480-cc1e-11e4-83a3-44fffeef9b83.png) 

back to the Choose a file button

**Comment by homm** [comment]
There is the [clearable](https://uploadcare.com/documentation/widget/#option-clearable) option for manual reset. Also you can reset value by `widget.value(null)` from external javascript code.

**Comment by michaellouieloria** [comment]
https://uploadcare.com/documentation/javascript_api/#widget

here's the solution I used

var multiWidget = uploadcare.MultipleWidget('[role=uploadcare-uploader][data-multiple]');
multiWidget.value(null);
multiWidget.reloadInfo();

Thanks for the help

**Comment by dmitry-mukhin** [comment]
`widget.reloadInfo()` is not necessary here, as it's used request widget to load info from DOM (input's value), if it was changed somehow. `widget.value()` does this directly.
