### ISSUE TITLE
Unexpected behaviour when setting value in widget

### ISSUE THREAD

**Issue by aaunel** [uploadcare/uploadcare-widget#235]
Updating the widget with an existing UUID value triggers an upload. This feels unexpected for widget methods, and something you'd expect from calls within the files and uploads methods.

```javascript
// Set a file UUID or a CDN link as a value.
singleWidget.value('a9a1907e-b7af-4311-8d11-08f2d952aeb5');
```

When presenting options for a previously uploaded image, this appears to be the correct approach, no?

**Comment by homm** [comment]
What you mean by "triggers an upload"? I see only "loading info" progress with following code: http://jsbin.com/busaso/1/edit?js,output

**Comment by aaunel** [comment]
Modified to demonstrate what I'm referring to here http://jsbin.com/tanusidida/1/watch?js,console,output

**Comment by homm** [comment]
`onUploadComplete` is just shortcut to:

```js
widget.onChange(function(fileOrGroup) {
  fileOrGroup.promise().done(function(fileOrGroupInfo) {
    // onUploadComplete(fileOrGroupInfo) there
  });
});
```

It fires every time when value is changed and new value is ready.

Could you describe me your task and why this behavior doesn't suit you?

**Comment by aaunel** [comment]
Ok, it seems odd this triggers a full journey. Presumably in this case (of a value change) there has been no upload, I think?

I'm using the widget in Angular and save a $resource on the back of a successful upload. Ideally this is suited to return to the image thumbnail in the app to remove or change the image later. When returning to an already-uploaded image, I need the widget to present a clearable action ('remove' button) - `.value()` does this but also triggers a successful upload again.

fwiw, this is derived from the [Uploadcare Angular directive](https://github.com/uploadcare/angular-uploadcare).

**Comment by aaunel** [comment]
Any further thoughts on this?

**Comment by dmitry-mukhin** [comment]
@aaunel, there is no upload going on if you set widget's value to already existing file. In this case `onUploadComplete` name may be misleading, but as @homm already mentioned, this is just a shortcut. I assume you may change your code to factor the real behavior (not perceived).

Let me know if I'm missing something here.

**Comment by aaunel** [comment]
Ok, fair enough, I can see `onUploadComplete` triggering for this - but yes, somewhat misleading. I'm not getting duplicates in Uploadcare storage or anything.

So, I'm reading from the file within `onChange`, how can I tell whether I'm dealing with a file that's already uploaded versus a newly uploaded file? Or, should I do this from within my own code?

```
widget.onChange(function(file) {
  if (!file) return; // removed
  file.done(function(fileInfo) {
    // equivalent to onUploadComplete
    if (fileInfo.alreadyUploaded) { ... } // ?
  });
});
```

**Comment by dmitry-mukhin** [comment]
@homm should be able to give you precise answer.

**Comment by homm** [comment]
@aaunel I think in your case you don't need to distinguish already uploaded files and not. For example, If user selects one already uploaded file instead of another, you still need to save your model. Instead you need a way to distinguish `onChange` and `onUploadComplete` events from initial value and user-selected value. One way to do this is attach `onChange` handler with delay. In most cases simple `setTimeout(fn, 0)` would be enough. Other way is set some flag before set your initial value, ignore first `onChange()` event with the flag and change flag back.

**Comment by aaunel** [comment]
> set some flag before set your initial value

Cool, this is what we imagined would work best. I'll do it this way. Thanks for all the help; will close this issue since it doesn't appear to be a bug in that case.
