### ISSUE TITLE
Force system dialog not working on android

### ISSUE THREAD

**Issue by SturmDrangAltaar** [uploadcare/uploadcare-widget#248]
Hi

I'm using the widget with data-system-dialog="true" attribute.
The dialog pops up on desktop and ios, but nothing happens on android. Tested on chrome in android 4.4.3 and 4.4.4

**Comment by homm** [comment]
Which browser and which widget version do you use?

Could you try to set "system dialog" option on [configure page](https://uploadcare.com/widget/configure/) and try the widget right on the page?

**Comment by SturmDrangAltaar** [comment]
Yep, works there.
Let me try defining the option in the HEAD and see if that makes a difference

**Comment by SturmDrangAltaar** [comment]
@homm 
OK, no idea what's going on, but I think it might be related to the meteorjs plugin I'm using. I'll move it over there. Thanks

**Comment by homm** [comment]
Could you share some test page so we can try to find out the reason of the issue?
