### ISSUE TITLE
Coordinates for crop area

### ISSUE THREAD

**Issue by leandono** [uploadcare/uploadcare-widget#262]
Hello, I'm using `uploadcare.openDialog` to show a window that only has the functionality of cropping (I can do that setting `{ tabs: '', crop: <size> }` in the openDialog method). When the window shows up, the coordinates (x,y) of the crop area always appears on the middle of the image... there is a way to control that coordinates to setup where put the crop area?

Thanks

**Comment by homm** [comment]
Yes. You can specify selected area as part of selected file in URL operations. For example:

```js
uploadcare.openDialog(
  uploadcare.fileFrom(
    'uploaded',
    'https://ucarecdn.com/f96abe6f-ac6f-437e-a5d2-9a395fe1bfab/-/crop/1200x1500/3000,1100/',
    {publicKey: 'demopublickey'}
  ), {
    crop: 'free',
    publicKey: 'demopublickey',
  }
);
```


PS. Please, send questions (not issues) to support@uploadcare.com.

**Comment by leandono** [comment]
Thanks, and sorry for put the question here.
