### ISSUE TITLE
Documentation for self-hosting?

### ISSUE THREAD

**Issue by spiffytech** [uploadcare/uploadcare-widget#276]
Is it possible to have the widget upload directly my own server, without going through uploadcare? Is there documentation on what API my server should support for this?

**Comment by dmitry-mukhin** [comment]
The widget uses [Upload API](https://uploadcare.com/documentation/upload/). If you'll implement this, you'll be able to send files to your own server.

The part related to getting files from users' cloud servives and social networks is proprietary though. In essence it just shows list of available files via URLs and widget is using "upload from URL" API.

Hope that answers your question.
Feel free to follow up via help@uploadcare.com
