### ISSUE TITLE
Could not change CSS from chrome devtools 

### ISSUE THREAD

**Issue by evaletolab** [uploadcare/uploadcare-widget#277]
Hi,
I found a strange issue when I trying to use the devtools from chrome ( 45.0.2454.101 Ubuntu 15.04 (64-bit)) with uploadcare (v2.5.5) on my web application. The CSS editor is blinking. It seems, that there is a continuous refresh requested and you can't change anything. It's easy to test the issue [on your tutorial page](https://uploadcare.com/quick_start/), you just need to open the devtools, inspect an element and try to modify the css 
![](http://www.ucarecdn.com/1d8a134a-9bfd-409f-a3a2-11d487f3b8b0/Capturedu20151012154040.png)

Any idea?

**Comment by dmitry-mukhin** [comment]
Hi there!
[This](http://stackoverflow.com/questions/32924531/why-uploadcare-is-repainting-html-tag-every-n-ms/32926475#32926475) should sort you out!

Feel free to comment or contact us at help@uploadcare.com if it does not.

**Comment by evaletolab** [comment]
perfect, merci beaucoup!
