### ISSUE TITLE
loop initialization with new version of uploadcare 2.5.x

### ISSUE THREAD

**Issue by sinsunsan** [uploadcare/uploadcare-widget#281]
After having upatated to latest version of uploadcare in my installation, 2.5X  with jquery 2.1, I had a flickering effect. After investigating it I notice html element was like disapearing and reapearing. 
I put a watch on it and figure out 
that 
this function was being called repeteadly 
````
uploadcare.namespace('', function(ns) {
    var cleanup, dataAttr, initialize, initializeWidget, selector;
    dataAttr = 'uploadcareWidget';
    selector = '[role~="uploadcare-uploader"]';
    ns.initialize = function(container) {
      if (container == null) {
        container = ':root';
      }
      return initialize($(container).find(selector));
    };
````

and called that function from jquery.sizzle 
````
if ( newSelector ) {
    try {
      push.apply( results,
        newContext.querySelectorAll( newSelector )
      );
      return results;
    } catch(qsaError) {
    } finally {
      if ( !old ) {
        context.removeAttribute("id");
      }
    }
````

Uploadcare is not compatible with jquery 2.x branches ?

**Comment by dmitry-mukhin** [comment]
The Uploadcare plugin searches for new widgets on the page every 100ms. This is called live initialization. Internally the plugin uses jQuery (which uses Sizzle selector engine) and this is how Sizzle actually works: it adds id elements to the root element of the search scope before the querying and remove it after. You can verify this with a simple example:

```html
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script>
  setInterval(function() {
    $.find('[attr]', document.documentElement);
  }, 200);
</script>
```

If you want to avoid flicking, you have two options. You can disable live initialization at all by adding UPLOADCARE_LIVE = false; to js code. Or you can add any custom id attribute to the html tag. Sizzle will not change it.

In the future, we are planning to use MutationObserver to watch for the new widgets on the page.

Sorry for the copypasta.

**Comment by sinsunsan** [comment]
I have nothing against this behavior, but in the version 1.5.x it didn't do
this effect.
With the more recent version it produce a important overload on my dev
tools.
For example, I can't test css styles in the dev tool, as it seem like
replaced (every 100ms).
So once I type, it get erased.

Also listening to my computer fans, it seem to overload the page.

Per aps it is due the an interaction with angular, than manage the page
dom, per aps forcing it to rerender the page ?
Do you suggest initializing manually with angular ?

What has changed between 1.5 and 2.x that could cause this performance
difference ?

**Comment by homm** [comment]
Sébastien, that effects all from the Elements tab repainting in Chrome Dev Tools for sure.

You have two options to fix it. You can disable live initialization at all by adding `UPLOADCARE_LIVE = false;` to js code. Or you can add any custom `id` attribute to the `html` tag. Sizzle will not change it every 100ms.

**Comment by markbao** [comment]
Thank you - I was wondering why Chrome DevTools' elements pane just wasn't working.

**Comment by sinsunsan** [comment]
It is 1 year and more that I posted this issue. 
On another project, I used latest version of uploadcare widget. Forget about that issue, and have little css debuging to do. So it does not disturbed me so much. 
But I noticed that I was unable to edit the css directly in chrome debug dev because of this annoying effect that refresh everything... 

But I forget a bit about this issue, and thought it was another problem. 

But in fact it was this very issue and it is 1 months ++ I am working with this annoying default because of uploadcare. 

I suggest that you set UPLOADCARE_LIVE = false; by default, because many people probably are loosing time like me. 

And it is a problem that is difficult to put a name on to search in google. Like a clear debug error message.

I do not know why it is not fixed in a more stable way now. @dmitry-mukhin

**Comment by dmitry-mukhin** [comment]
Lucas,

while we still haven't implemented MutationObserver (we're working on widget 3 at the moment), the problem affect far less users compared to changing default to disable live init.

Do you think that adding a message to JS console (e.g. how Facebook does this) will make you happy?

@Zmoki @homm please pitch in on this.

**Comment by sinsunsan** [comment]
If you are able to detect who have this problem yes a console log would be a way to at least guide them to the solution. 

The fact that a library is able to make chrome debugger unusable at least regarding its live css  editor (right panel in the element tab)  seem to me strange anyway.

**Comment by dmitry-mukhin** [comment]
In any case changing this default breaks compatibility, so I'd rather press for implementing [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) workflow.

**Comment by maxfi** [comment]
> If you are able to detect who have this problem yes a console log would be a way to at least guide them to the solution.

I agree with @sinsunsan. This issue made my dev tools almost unusable and pegged my CPU. It's also hard to track down and troubleshoot. Although it is [mentioned in the docs](https://uploadcare.com/documentation/widget/#initialization) a `console.log` referencing the docs would definitely be a good idea!

**Comment by williamli** [comment]
I too wasted a few hours on this (and it slowed down my dev time for about a day till I notice the flickering)

**Comment by williamli** [comment]
Regardless of what `UPLOADCARE_LIVE` 's default settings should be, this "feature" should be listed as part of the documentation instead of hidden as a GitHub issue. This would have saved a lot of our time if this is documented in the public doc.

**Comment by kyle-ssg** [comment]
This needs to be added to the docs!

**Comment by Zmoki** [comment]
Ok, thank you! We'll update our docs soon. And with next major version of the widget we'll change this behavior of the widget.
