### ISSUE TITLE
Throw something when widget is actually not initialized

### ISSUE THREAD

**Issue by homm** [uploadcare/uploadcare-widget#284]
For now `uploadcare.Widget(".class")` always successful, even if `.class` doesn't exist or there are many `.class` tags on the pages. An error should be thrown in the first case and warning in the second.

**Comment by ZNick1982** [comment]
I found several widget initialisators in the code: ns.Widget, ns.SingleWidget,  ns.MultipleWidget
Should I add this check only for ns.Widget or I should modify other methods to?

**Comment by homm** [comment]
They are all use [`initializeWidget`](https://github.com/uploadcare/uploadcare-widget/blob/master/app/assets/javascripts/uploadcare/widget/live.coffee#L22-L29) internal.

**Comment by ZNick1982** [comment]
Yes I saw it, Ok, I will update  initializeWidget method

**Comment by homm** [comment]
Yes, please.

The difference between `ns.Widget` and `ns.[Single/Multiple]Widget` is the first doesn't check the type of the widget while the second does. This can be important when you want to be sure that the widget is single or multiple because they have different API.

**Comment by ZNick1982** [comment]
Done with pr: https://github.com/uploadcare/uploadcare-widget/pull/310
