### ISSUE TITLE
Disable camera for not HTTPS

### ISSUE THREAD

**Issue by homm** [uploadcare/uploadcare-widget#306]
Starting from version 47, Chrome doesn't allow to initialize camera on HTTP sites. Furthermore, there is no way to test is camera will be blocked in the current browser due to HTTP.

The preferred solution is to disable camera at all for HTTP sites (except localhost). Additionally, camera tab should log some sensible reasons to console if it was disabled.

**Comment by ZNick1982** [comment]
Done with pull request: 
https://github.com/uploadcare/uploadcare-widget/pull/307

**Comment by ZNick1982** [comment]
Remove tab in case of HTTP connection in pull request: https://github.com/uploadcare/uploadcare-widget/pull/309
