### ISSUE TITLE
Confirmation before remove & Edit button

### ISSUE THREAD

**Issue by fabien** [uploadcare/uploadcare-widget#330]
Currently, it can be confusing to users to only find a `remove` button and not really a button to `edit` previously uploaded files (replace or in the case of multiple uploads, add/remove/reorder).

Additionally, because of the `remove` button takes visual precedence (mostly because it's not an actionable word, it just shows the current filename/group count) over the `uploadcare-widget-file-name uploadcare-link`-marked href, it's pretty easy to click `remove` by mistake.

Even without this issue, it would be nice to have a confirmation dialog for this option, or at least a way to intercept the `remove` call before it's actually executed. With such a callback-mechanism in place, you could easily craft your own dialog if needed.

**Comment by homm** [comment]
You can implement your own Remove button with any conformations and use widget's API `widget.value(null)`. Does it suits you?

**Comment by fabien** [comment]
In that case, I should probably hide the `remove` button using jQuery, correct?

**Comment by homm** [comment]
No, you can just do not set `data-clearable` attribute.

**Comment by fabien** [comment]
Aha, interesting! Thanks.

Another (unrelated) question, if I show the widget as a panel (using openPanel), it appears that after clicking done, it will always close/hide itself. Is there a way to keep it open? I was thinking, as a workaround I'd re-open it after closing (deferred).

**Comment by homm** [comment]
There is no way to keep it open, because this why the panel and dialog works: the promise will be resolved when user selects files. There is no way to resolve promise twice, so the only way is no open another panel (if you need it).

**Comment by fabien** [comment]
OK, thanks. You can close this issue.
