### ISSUE TITLE
How i can destroy all widgets?

### ISSUE THREAD

**Issue by anorudes** [uploadcare/uploadcare-widget#331]
Hello, can you help me with destroy all widgets?

I want make this:
uploadcare.remove('body');
uploadcare.initialize('body');

or
uploadcare.reset('body');

**Comment by dmitry-mukhin** [comment]
is this a #328 duplicate?

**Comment by nd0ut** [comment]
Duplicate of https://github.com/uploadcare/uploadcare-widget/issues/328
