### ISSUE TITLE
Help needed - Image display in website??? with code...

### ISSUE THREAD

**Issue by rossdraper2015** [uploadcare/uploadcare-widget#337]
i have a website that is very nearly complete. my last and final obsticle is image uploading. and as you can imagine as a noobie i have been through the thik and thin looking for a way to impliment uploading...(6.15 AM lol)i tried the hard way to begin with using php and got nowhere, i eventually stumbled upon a widget embedment UPLOADCARE...

i am now using jscript to display the image.. however i have 1 issue...

instead of displaying the image, all im getting is the text/ascii displayed UUID/URL rather than it being displayed as the img ...
i know sumwhere its down to me using 2 jscript suggestions as i have sort of mixed the input part with another suggestion of onchange... so i basically really need sum1s help with a workaround...

i would be most greatfull if anybody can offer me a quikfix and i will indeed place you within the website credits... thank you.

here is the code...

<head>
<script>UPLOADCARE_PUBLIC_KEY = "c557ad102b8e86698602";</script>
<script src="https://ucarecdn.com/widget/2.8.2/uploadcare/uploadcare.full.min.js" charset="utf-8"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>

<script type="text/javascript">

function imagepreview(input) {
if (input.files && input.files[0]) {
var filerd = new FileReader();
filerd.onload=function (e) {
$('#imgpreview').attr('src', e.target.result);
};
filerd.readAsDataURL(input.files[0]);
}
}
</script>
</head>

</body>

<div style="position:absolute; top:440; left:440;">
<input type="file" name="my_file" onchange="imagepreview(this);" role="uploadcare-uploader" /><br/>
<img id="imgpreview" alt="ImagePreview" />
</div>

</body>

**Comment by rossdraper2015** [comment]
<head>
<script>UPLOADCARE_PUBLIC_KEY = "c557ad102b8e86698602";</script>
<script src="https://ucarecdn.com/widget/2.8.2/uploadcare/uploadcare.full.min.js" charset="utf-8"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>

<script type="text/javascript">

function imagepreview(input) {
if (input.files && input.files[0]) {
var filerd = new FileReader();
filerd.onload=function (e) {
$('#imgpreview').attr('src', e.target.result);
};
filerd.readAsDataURL(input.files[0]);
}
}
</script>
</head>

</body>

<div style="position:absolute; top:440; left:440;">
<input type="file" name="my_file" onchange="imagepreview(this);" role="uploadcare-uploader" /><br/>
<img id="imgpreview" alt="ImagePreview" />
</div>

</body>

**Comment by dmitry-mukhin** [comment]
@rossdraper2015 this is really not the place to ask for support.
take a look at [this example](https://uploadcare.com/cookbook/widget_visual/#uploaded-image-preview) and if it does not help, write us an email.

**Comment by rossdraper2015** [comment]
sorry new to github ,have been advised that i could find what i am looking for here...need to familurise with github though....
[uploadcare-imageupload&preview.txt](https://github.com/uploadcare/uploadcare-widget/files/243498/uploadcare-imageupload.preview.txt)

**Comment by rossdraper2015** [comment]
have been on the uploadcare page, but it is jscript that i am unfamilure with...had to use it though to use the widget...
