### ISSUE TITLE
Crop settings don't apply to images if dialog is closed before uploading is done

### ISSUE THREAD

**Issue by homm** [uploadcare/uploadcare-widget#348]
When crop is set (for example `data-crop="500x500 minimum"`), user drop some images to the widget or dialog and closes the dialog as soon as possible, the default crop settings apply only the files which are uploaded at the moment.

**Comment by joeyvmason** [comment]
I am noticing this as well. It seems that you can't really use this crop functionality because of this. A quick fix might be to just force the user to crop to desired dimensions before allowing them to close the modal.

**Comment by nd0ut** [comment]
@homm It seems that it is already fixed.
Check the screencast please.
https://www.useloom.com/share/f5e967c3d6784e3988332cc9e1e08ebe
