### ISSUE TITLE
jQuery 3 compatibility

### ISSUE THREAD

**Issue by flipvh** [uploadcare/uploadcare-widget#350]
Hi Guys,

We were checking if we could update to jquery 3 - because our app doesn't support older browsers anyway - but it seems some code for the uploadcare-widget needs to be updated to be compatible with jquery 3? 

link to jquery blog: 
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

**Comment by dmitry-mukhin** [comment]
Flip,

can you please check if it works with jQuery 3 out of the box? You can do that by using widget version that is not bundled with jQuery.

Secondly, bundled jQuery is in isolated Uploadcare scope and should not clash with jQuery used on host page.

Please let us know what you find out, thanks!

**Comment by indigoram89** [comment]
после загрузки изображения вместо кнопки появляется его название.
после клика на название должен открыться виджет с загруженным изображением.

при использовании jquery 3 здесь возникает ошибка.

не хотелось бы подгружать полную версию виджета, когда jquery уже есть на странице.

**Comment by dmitry-mukhin** [comment]
@homm @Zmoki ^

**Comment by mikegleasonjr** [comment]
I don't know about the previous comment but it does work when you just invoke the dialog.

As soon as you add compression, or you specify validators, the plugin fails with all sorts of jQuery errors.

**Comment by sebdec** [comment]
Indeed, it doesn't seem to work completely with jquery3 :/

**Comment by fabien** [comment]
Any updates on this?

**Comment by Zmoki** [comment]
Hey there,

Thanks for your patience. We've implemented the fixes for jQuery 3 compatibility.
The version including the fixes is `2.10.4`
