### ISSUE TITLE
Video review step not working in Chrome

### ISSUE THREAD

**Issue by olizilla** [uploadcare/uploadcare-widget#356]
When uploading a video, using the widget webcam video recording feature, and with `{previewStep:true}` the usual video playback / review step is no longer appearing in Chrome 53.0 on OSX 10.11.6

I now get a message that says:

```
Add this file

record.webm, 0b
```

<img width="629" alt="screenshot 2016-09-28 17 16 13" src="https://cloud.githubusercontent.com/assets/58871/18922638/67494d2a-85a1-11e6-8e34-9700c8652309.png">

and no playback / review window. On Firefox 49.0.1 the same code does show the preview step after recording.

<img width="734" alt="screenshot 2016-09-28 17 31 47" src="https://cloud.githubusercontent.com/assets/58871/18922656/76cbbd5a-85a1-11e6-9683-27f0e4d5034e.png">

**Comment by homm** [comment]
@olizilla Could you try the same on this page?
https://uploadcare.com/widget/configure/

Which widget version you are using?

**Comment by olizilla** [comment]
Will do. We're using 2.10.0 from:
https://ucarecdn.com/widget/2.10.0/uploadcare/uploadcare.full.min.js

**Comment by olizilla** [comment]
Yep, same result in an incognito window on the test page:

<img width="795" alt="screenshot 2016-09-28 17 39 31" src="https://cloud.githubusercontent.com/assets/58871/18922979/98bb9380-85a2-11e6-9766-e77ceff36a59.png">

**Comment by homm** [comment]
Do you see any messages in Developer Tools?

I've tested on two computers with the same Chrome & OS X versions and can't reproduce the issue.

**Comment by olizilla** [comment]
Most odd. A killall on chrome has fixed it. Thanks for you time!

**Comment by caseyjenks** [comment]
I have a few users, who use this feature heavily running into this issue. Killing Chrome and re-booting fixes it, but is there any way to prevent a 0B file from being uploadable?

**Comment by dmitry-mukhin** [comment]
@caseyjenks you can use [file validation](https://uploadcare.com/cookbook/validation/). for local files you can effectively block uploads if filesize is too small.
