### ISSUE TITLE
The widget makes Chrome element inspection impossible by endlessly looping the HTML

### ISSUE THREAD

**Issue by rebelliard** [uploadcare/uploadcare-widget#366]
Whenever I include the UploadCare widget on my app, the Widget apparently causes Chrome to update the HTML endlessly, which makes modifying a style using the Inspector tool impossible!

![Video proof](https://dl.dropboxusercontent.com/u/13395910/dnd/github/uploadcare-chrome-loop.gif)

I am sure it is the widget because as soon as I remove it, the behavior stops.
* jQuery 2.2.4
* Bootstrap 3.3.7

**Comment by dmitry-mukhin** [comment]
this is a known issue/feature:
http://stackoverflow.com/a/32926475/3448
