### ISSUE TITLE
Can't load local images on Firefox?

### ISSUE THREAD

**Issue by rebelliard** [uploadcare/uploadcare-widget#367]
Proof: ![No firefox](http://g.recordit.co/0cuwHcr88d.gif)

**Comment by dmitry-mukhin** [comment]
Rafail,

unfortunately, this is not something that helps us. Can you please answer the following:

what is the widget version?
what is ff version?
does the same happens on [this page](https://uploadcare.com/widget/configure/) or in your dashboard?
is there anything interesting in console?
does the same page behaves well on other browsers?
do remote uploads work?

**Comment by rebelliard** [comment]
- Widget 2.10.1
- Firefox 50
- Yes it happens on your configuration page: http://recordit.co/Me3xqzVPOG
- Nothing on the Console https://www.dropbox.com/s/8cn2g6pswhrgc7y/Screenshot%202016-11-27%2011.12.58.jpg?dl=0
- Remote uploads work fine

**Comment by dmitry-mukhin** [comment]
@homm @Zmoki please look into it.

**Comment by dmitry-mukhin** [comment]
[fixed in 2.10.2](https://uploadcare.com/changelog/#widget-2-10-2)
