### ISSUE TITLE
Panel inside form

### ISSUE THREAD

**Issue by bruceborrett** [uploadcare/uploadcare-widget#370]
I am trying to use an "openPanel" inside a multi-step "wizard" form. Once the user has selected files, they click next to go to the next step. I have two questions:

1. How can I prevent the panel from closing so that the user is able to go back to that step to change their selection? 
2. How can I trigger the "done" event when clicking the next button, rather then having to click the "done" button in the widget?

**Comment by homm** [comment]
1. If user goes back, you can open dialog again providing previous selected files via first argument. See [Upload Dialog and Panel section in Javascript API](https://uploadcare.com/documentation/javascript_api/#dialog)
2. You can use `dialogApi.resolve()` function. See [Dialog API section in Javascript API](https://uploadcare.com/documentation/javascript_api/#dialog-and-panel-objects).
