### ISSUE TITLE
French typo: patientier > patienter

### ISSUE THREAD

**Issue by bartclaeys** [uploadcare/uploadcare-widget#371]
There is a french typo in the language locale (fr.js.coffee):

`uploading: 'Envoi en cours... Merci de patientier.'`

should be

`uploading: 'Envoi en cours... Merci de patienter.'`

**Comment by Zmoki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [French typo: patientier > patienter](https://trello.com/c/KaZhv5Ur/127-french-typo-patientier-patienter)

**Comment by Zmoki** [comment]
@bartclaeys thank you! I fixed this typo. This update will ship with next version of widget.
