### ISSUE TITLE
Record Tab Not Working on Safari

### ISSUE THREAD

**Issue by bmordan** [uploadcare/uploadcare-widget#375]
The camera will not initialise on Safari

<img width="1434" alt="screen shot 2017-03-01 at 09 56 48" src="https://cloud.githubusercontent.com/assets/4499581/23454976/f5ef1450-fe65-11e6-8738-a247fa2b3ec7.png">

Uploadcare dialog error – undefined
(anonymous function) — bundle.js:91559
s — uploadcare.full.min.js:9:2712
fireWith — uploadcare.full.min.js:9:3471
(anonymous function) — uploadcare.full.min.js:9:4449
(anonymous function) — uploadcare.full.min.js:17:3447
(anonymous function) — uploadcare.full.min.js:9:4030
s — uploadcare.full.min.js:9:2712
fireWith — uploadcare.full.min.js:9:3471
(anonymous function) — uploadcare.full.min.js:9:4449
__reject — uploadcare.full.min.js:33:6255
(anonymous function) — uploadcare.full.min.js:33:1034
dispatch — uploadcare.full.min.js:10:6969
handle — uploadcare.full.min.js:10:5052
Selected Element
<section class="row p-y-1">…</section>

**Comment by dmitry-mukhin** [comment]
Camera tab requires browser to support various APIs ([can i use](http://caniuse.com/#feat=stream)). Furthermore, most browsers restrict camera usage to secure pages only (i.e. Chrome). The tab will "magically" work when Safari adds support for those APIs.

**Comment by homm** [comment]
@bmordan Could you check the widget on the page: https://uploadcare.com/widget/configure/?tabs=file%20camera
Does the error also appear? If no, could you provide URL where we can see the error.

**Comment by dmitry-mukhin** [comment]
@Zmoki @homm can we reproduce this?

**Comment by Zmoki** [comment]
This is not actual, cause we update camera tab in v2 and v3
