### ISSUE TITLE
Including uploadcare widget causes continuous DOM reflows

### ISSUE THREAD

**Issue by ajwootto** [uploadcare/uploadcare-widget#384]
Just having the widget included on the page appears to cause the DOM to reflow continuously, making it impossible to do anything like live editing CSS in the Chrome web inspector.

**Comment by dmitry-mukhin** [comment]
#277 :)

**Comment by ajwootto** [comment]
Sure that works as a temporary solution, but the javascript certainly shouldn't be doing this in general. You're breaking the chrome dev tools for anybody that uses this widget script the way it's intended.

**Comment by ajwootto** [comment]
You could just use standard javascript to do the attribute selector polling:
https://stackoverflow.com/questions/2694640/find-an-element-in-dom-based-on-an-attribute-value/16775485#16775485
and fall back to jQuery for older browsers.

**Comment by dmitry-mukhin** [comment]
@Zmoki @homm ^^
