### ISSUE TITLE
Uploadcare Dialog: Scroll within tab on iOS devices not working

### ISSUE THREAD

**Issue by levizimmerman** [uploadcare/uploadcare-widget#395]
I am using uploadcare-widget 3.0.1 from NPM. And can reproduce the scroll bug when I do the following:
- Open Uploadcare dialog by clicking on 'Choose Images';
- Choose to add photos from my Instagram (also occurs when using Facebook);
- When photos are loaded into the dialog it is not possible to scroll through the photos;

(This is tested on a iPhone 6S with iOS 10.3.3, also occurs within iOS simulator)

This is probably a CSS bug. I have inspected the elements from tab__content to html,body tag. I see a lot of 'overflow:hidden' statements. I am not sure if this has anything to do with it. 

Furthermore I can see an iframe is used to load in the external content from Instagram (or Facebook). Maybe this contributes to the issues, but still I am not sure.

Finally I have tried to reproduce the problem on Android devices, but there the dialog seems to be functioning as it should.

![schermafbeelding 2017-07-11 om 17 15 15](https://user-images.githubusercontent.com/12231393/28076449-0de1060c-665f-11e7-8c0e-6d1801d1ee66.png)

**Comment by Zmoki** [comment]
@levizimmerman thank you for reporting! I know about these problem and work on it. I'll release new version of the widget with fix soon (today or tomorrow).

**Comment by levizimmerman** [comment]
@Zmoki any update yet?

**Comment by Zmoki** [comment]
@levizimmerman we now release the `3.1.0` version ([changelog](https://github.com/uploadcare/uploadcare-widget/blob/master/HISTORY.markdown#310-19072017)). Update and check =)

**Comment by levizimmerman** [comment]
@Zmoki Just installed the new update and checked out the fix on an iOS device. Everything seems to be working properly. 

Good job and thank you!
