### ISSUE TITLE
Closing script tag in files causing rendering errors

### ISSUE THREAD

**Issue by aaronmiler** [uploadcare/uploadcare-widget#404]
The script tags [here](https://github.com/uploadcare/uploadcare-widget/blob/5a3fadd8f643e4a708481c84b888cd8aefffe663/app/assets/javascripts/uploadcare/utils/warnings.coffee#L32) in warnings.coffee are causing rendering errors in my test environment.

For the time being, I've worked around the problem by using `gsub` on the javascript blob that gets inserted into the document, but this feels like a hack.

Let me know if you have any questions, of if you'd like to discuss further.

**Comment by nd0ut** [comment]
@aaronmiler Hello! We are so sorry for a such long answer.

Tell me please what kind of test environment are you using? PhantomJS or something else? How to reproduce it?

**Comment by aaronmiler** [comment]
I'm using Phantom.JS, with Capybara in Ruby. 

Not too much code is required. In my test environment Webpack compiles the JS bundle, and inserts it directly into the page in a `<script>` tag.

So I believe the only code needed to reproduce, is to put a blob of compiled JS onto the page that includes the Uploadcare widget, and this should cause PhantomJS to spit out a rendering error.

**Comment by jeetiss** [comment]
@aaronmiler we migrate from coffee script, and i think now it works, so i close the issue. feel free to reopen
