### ISSUE TITLE
How do I access locale strings at runtime

### ISSUE THREAD

**Issue by SpadarShut** [uploadcare/uploadcare-widget#413]
I'm making a react upload widget and need to access error strings to render in my component. 
How can I access translation strings from `uploadcare` object or somewhere else?

**Comment by Zmoki** [comment]
@SpadarShut hi!

You can get access to special undocumented (_sorry_) function that helps to get translations,

```javascript
let translate

uploadcare.plugin(uc => translate = uc.locale.t)

console.log(translate('dialog.tabs.preview.done')) // returns 'Add'
```

Now `translate` is a function that takes one argument - the path to the desired phrase, based on structure of locale https://github.com/uploadcare/uploadcare-widget/blob/master/app/assets/javascripts/uploadcare/locale/en.js.coffee

**Comment by SpadarShut** [comment]
@Zmoki thanks! Works like a charm!
