### ISSUE TITLE
Video Quality When Recording On The Spot 

### ISSUE THREAD

**Issue by michaelniepel** [uploadcare/uploadcare-widget#422]
When recording a video on iOS the video is poor quality: 480×360 (landscape) or 360×480 (portrait).

Setting 1080p HD at 60 fps on the device as default record quality does not help and the uploaded video is still small (this article describes how it should behave with html media capture https://addpipe.com/blog/video-quality-when-recording-videos-from-safari-on-ios-through-html-media-capture/).

Is this something that can be fixed in the widget?

**Comment by Zmoki** [comment]
@michaelniepel thank you for report!

You try to record video on "Camera" tab or by clicking on "Choose a local file" on "Local Files" tab?

**Comment by michaelniepel** [comment]
@Zmoki "Choose a local file" -> Take Video -> record -> Use Video. "Local Files" tab just takes me back to to "Choose a local file"

When I use "Choose a local file" -> Photo Library and select a saved video, the video is fine.

**Comment by dmitry-mukhin** [comment]
@michaelniepel in case you use "local file" tab, it's up to the os to record the video. it's not HTML media capture, but your native camera app that makes actual recording.

**Comment by michaelniepel** [comment]
@dmitry-mukhin yes I know, so it's rather iOS "feauture"/issue than UC's widget?

**Comment by dmitry-mukhin** [comment]
Exactly. Widget has no control over native apps :(
We just tell the OS "hey give us some local file(s)" and it decides what options to show to a user.
It does not differ from a common _input type=file_, you can check that yourself.

Let me know if we can close this.
