### ISSUE TITLE
Prevent auto hide of dialog

### ISSUE THREAD

**Issue by abhinavmsra** [uploadcare/uploadcare-widget#426]
I am trying to handle opening and closing of dialog manually.

My code looks as follows:

```
static pick(options = {}) {
    Uploadcare
      .openDialog(null, {
        publicKey: UPLOADCARE_PUBLIC_KEY,
        ...DEFAULT_OPTIONS,
        ...options
      })
      .done(result => {
        result.done(file => {
          // onUploadSuccess code goes here
        });
      });
  }
```

However, upon selecting the file and clicking `ADD` button on the dialog, the dialog closes immediately but the `result.done` callback is triggered only after the file is uploaded.

Between the duration the dialog is closed and the file is actually uploaded, I need to provide feedback to the user that the file is being uploaded.

Is there any way I can defer the dialog close until the file is uploaded? 

On [Filestack](http://filestack.com/), they solve this issue by presenting a progress bar inside the dialog.

**Comment by dmitry-mukhin** [comment]
you can enable "preview step" and your users will see the progress in the dialog.
https://uploadcare.com/docs/uploads/widget/config/#option-preview-step

let us know if this not what you're looking for.

**Comment by dmitry-mukhin** [comment]
you can try to hide/disable close button and keyboard shortcuts via JS/CSS
