### ISSUE TITLE
Multiupload widget not working

### ISSUE THREAD

**Issue by f6v** [uploadcare/uploadcare-widget#428]
I'm using `uplodcare-rails`, but seems like the problem is related to the widget(version 3.2.2).
I have a widget to upload multiple files, when clicking on a "Choose images" button, I get following error:

`book_form-8ddc991aa9f839aa0028.js:22 Uncaught TypeError: p is not a constructor
    at Object.c.openPanel (book_form-8ddc991aa9f839aa0028.js:22)
    at Object.c.openDialog (book_form-8ddc991aa9f839aa0028.js:22)
    at l.__openDialog (book_form-8ddc991aa9f839aa0028.js:22)
    at l.openDialog (book_form-8ddc991aa9f839aa0028.js:22)
    at HTMLButtonElement.<anonymous> (book_form-8ddc991aa9f839aa0028.js:22)
    at HTMLButtonElement.dispatch (book_form-8ddc991aa9f839aa0028.js:60)
    at HTMLButtonElement.m.handle (book_form-8ddc991aa9f839aa0028.js:60)`

Here's where it happens(minified version):

![image](https://user-images.githubusercontent.com/13019221/36072147-e4aaddde-0f1a-11e8-9120-ee2712006950.png)

Everything works locally, but when running in `production` environment, there's an error. The widget is inside a React component by the way. Here's a code snippet:

```
import React, { Component } from "react";
import uploadcare from "uploadcare-widget";

class Uploader extends Component {
  componentDidMount() {
    const { onImagesChange, fileIds } = this.props;
    const widget = uploadcare.Widget(this.uploader);
    widget.value(fileIds);
    widget.onChange((fileGroup) => {
      Promise.all(fileGroup.files()).then(values => onImagesChange(values))
    });
  }

  render() {
    return (
      <input type="hidden"
        ref={input => this.uploader = input}
        data-images-only
        data-multiple
        data-crop="free"
      />
    );
  }
}

export default Uploader;

```

What could be the issue? Thanks in advance!

**Comment by f6v** [comment]
An update: I've disabled webpack uglify plugin, and it seems to work fine. UglifyJS was enabled only in production environment, not in development, that's why it worked locally. Any tips how to make it work with UglifyJS?

**Comment by dmitry-mukhin** [comment]
@Zmoki

**Comment by Zmoki** [comment]
@f6v which versions of `webpack` and `uglifyjs-webpack-plugin` packages do you use? Can you provide your config for UglifyJsPlugin?

**Comment by f6v** [comment]
Here's my package.json:

```
{
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^3.1.1",
    "babel-preset-react": "^6.24.1",
    "coffeescript": "1.12.7",
    "humps": "^2.0.1",
    "immutability-helper": "^2.6.2",
    "immutable": "^3.8.2",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-sortable-hoc": "^0.6.8",
    "uglifyjs-webpack-plugin": "^1.0.0-rc.0",
    "uploadcare-widget": "^3.2.1"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.9.7"
  }
}
```

I should probably try updating `uglifyjs-webpack-plugin`, I've been using specified version due to some webpacker quirks...

**Comment by Zmoki** [comment]
Sorry, I can't reproduce your error. I tried webpack@3.8.1, webpack-dev-server@2.9.7 and uglifyjs-webpack-plugin@1.0.0-rc.0 and my app worked fine.

In your webpack config you set custom config for uglify plugin?
