### ISSUE TITLE
Images are not previewed when using openDialog()

### ISSUE THREAD

**Issue by MatthiasKunnen** [uploadcare/uploadcare-widget#440]
I open the dialog via 
```TypeScript
await uploadcare.openDialog(
    ['https://ucarecdn.com/9dd2f080-cc52-442d-aa06-1d9eec7f40d1/'],
    {imagesOnly: true, crop: '5:8'},
);
```
This just show the first tab, in my case, local files. I expect the user to be able to edit the previously uploaded file.

**Comment by MatthiasKunnen** [comment]
Doesn't this conflict with the documentation at [https://uploadcare.com/docs/uploads/widget/predefined/](https://uploadcare.com/docs/uploads/widget/predefined/)?

**Comment by MatthiasKunnen** [comment]
@homm I would like to reiterate that the documentation mentions the following:

> If you set the input value externally and trigger the DOM change event, it affects the widget. For instance, setting it to a **file UUID or a CDN link** will result in a predefined file loaded into the widget. You can do this for a live widget or even before it loads.

**Comment by homm** [comment]
This is documentation for `value` attribute of `<input>` HTML element.

See documentation for javascript `uploadcare.openDialog` function here: https://uploadcare.com/docs/api_reference/javascript/dialog_panel/

**Comment by nd0ut** [comment]
@MatthiasKunnen has your issue been resolved? Can I close it?

**Comment by MatthiasKunnen** [comment]
Yes, apologies. It would be a nice quality of life improvement if a CDN link or file UUID could be passed though.
