### ISSUE TITLE
Any chance of removing jQuery as a dependency in the future?

### ISSUE THREAD

**Issue by juhaelee** [uploadcare/uploadcare-widget#442]
Hate to be that guy, but I don't use jQuery in my application and I'd hate to import jquery just for the filepicker. Is there any chance that in the future this widget will remove jQuery as a dependency?

Besides that, amazing widget and thank you so much for all the hard work!

**Comment by Zmoki** [comment]
@juhaelee thank you for feedback!

We will soon start working on a new major version of the widget, which will be written in a pure modern JavaScript and without dependencies.

We will inform about the changes in [Twitter](https://twitter.com/Uploadcare) and [changelog](https://uploadcare.com/changelog/).

**Comment by stefankp** [comment]
Are you still planning on removing jQuery?
