### ISSUE TITLE
Wrong image getting displayed when multi files are dropped on single uploads

### ISSUE THREAD

**Issue by TwunTee** [uploadcare/uploadcare-widget#443]
When two or more images are being dragged and dropped into the widget which can accept only one image, the first image gets uploaded but the widget shows the second image and when you click on done and open the widget again, the first image will be visible. 

Expected Result: The widget should not accept the second image and should raise a error message informing it is a single image uploader.

**Comment by nd0ut** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Widget: wrong preview when dnd many images and single upload](https://trello.com/c/sIibNHGR/260-widget-wrong-preview-when-dnd-many-images-and-single-upload)

**Comment by nd0ut** [comment]
@TwunTee Thank you for the feedback!

We started work on that. I will notify you when it's done.

**Comment by nd0ut** [comment]
@TwunTee Hello!

We fixed it in the version `3.4.0`. It is available on [NPM](https://www.npmjs.com/package/uploadcare-widget) or by the link `https://ucarecdn.com/libs/widget/3.4.0/uploadcare.full.min.js`.

By `https://ucarecdn.com/libs/widget/3.x/uploadcare.full.min.js` it will be available soon.

You can view the full changelog [here](https://github.com/uploadcare/uploadcare-widget/blob/master/HISTORY.markdown#340-23052018).
