### ISSUE TITLE
Do you have a vuejs demo?

### ISSUE THREAD

**Issue by paulopmx** [uploadcare/uploadcare-widget#464]

**Comment by Zmoki** [comment]
@paulopmx not yet. But @evseevdev created the unofficial [vue component](https://github.com/evseevdev/vue-uploadcare), you can see how he implemented the vue wrapper [here](https://github.com/evseevdev/vue-uploadcare/blob/master/vue-uploadcare.vue).

Be careful, the component uses the old version of the widget in [npm dependencies](https://github.com/evseevdev/vue-uploadcare/blob/master/package.json#L24). The current version is `3.3.0`.
