### ISSUE TITLE
Option to close widget when clicking background overlay

### ISSUE THREAD

**Issue by weavermedia** [uploadcare/uploadcare-widget#491]
I'd like to see an option to enable closing of widget when user clicks the background overlay.

You may have your reasons for not enabling this by default but it should be up to us to decide what is best for our application.

If my users are used to this action for other kinds of modals in my app, they should have the same experience with your widget.

**Comment by optlsnd** [comment]
@weavermedia by default, the widget is being closed when a user double-clicks the overlay. Is it the behavior you're looking for or you want to change it?

**Comment by weavermedia** [comment]
I had no idea double-click closed the widget! I don't see any mention of it in the docs.

However, for me, double-click is a bad solution:
1. It has low affordance.
2. We do not use double-click anywhere else in our app, because...
3. I believe double-click should only be used for activating actions, especially on the web where double-click can cause more harm than good.

If the mechanics are there for double-click, how about an option for single-click?

And while we're at it, can we have an option for ESC key to close the widget too?

**Comment by weavermedia** [comment]
Great, thanks! 🎉
