### ISSUE TITLE
Error on handling "message" event, somehow connected with grecaptcha2

### ISSUE THREAD

**Issue by ru-web-designer** [uploadcare/uploadcare-widget#500]
### Summary

Looks like if grecaptcha2 by Google is present on the same page with uploadcare widget, it causes uncaught TypeError.

```
uploadcare.full.min.js:17 Uncaught TypeError: Cannot read property 'type' of null
    at uploadcare.full.min.js:17
    at dispatch (uploadcare.full.min.js:11)
    at m.handle (uploadcare.full.min.js:10)
```

![image](https://user-images.githubusercontent.com/3310192/44793471-010c2600-abaf-11e8-938d-18c6ee13bb81.png)

### How to reproduce

Just put uploadcare-widget (lastes 2.x or 3.x, doesn't matter) and Grecaptcha2 (https://www.google.com/recaptcha/api.js) on the same page. Uploadcare settings are:

```
var
  UPLOADCARE_LIVE = false,
  UPLOADCARE_AUTOSTORE = true,
  UPLOADCARE_PUBLIC_KEY = your_public_key;
```

### Effects

TypeError itself. Reports in a console.

Potentially makes impossible to upload files, but this effect is kind of heisenbug.

Uploader dialog still opens and looks like its working proper way.

**Comment by Zmoki** [comment]
@ru-web-designer thanks for the report! I'll try to reproduce that and return to you with an answer soon.

**Comment by ru-web-designer** [comment]
@Zmoki is this will be a fix for 3.x only, or for 2.x too?

**Comment by nd0ut** [comment]
@ru-web-designer We'll fix v2 in the near time too.
