### ISSUE TITLE
License

### ISSUE THREAD

**Issue by csamu** [uploadcare/uploadcare-widget#525]
Hello. What is the license?

The license file says its fully copyrighted while package.json says MIT.

Regards, 
Christoffer

**Comment by Zmoki** [comment]
@csamu hi! sorry for the long answer.

The right license is BSD 2-Clause “Simplified” License like in the [LICENSE](https://github.com/uploadcare/uploadcare-widget/blob/master/LICENSE) file.

package.json hold wrong license info, I fixed it. Thank you!
