### ISSUE TITLE
SVG image format support

### ISSUE THREAD

**Issue by nag5000** [uploadcare/uploadcare-widget#533]
`fileInfo.isImage` is false for svg files.

`test.svg` --> POST https://upload.uploadcare.com/base/?jsonerrors=1
GET https://upload.uploadcare.com/info/... --> 
```
{
  filename: "test.svg",
  is_image: false,          <---------
  is_ready: true,
  is_stored: true,
  mime_type: "image/svg+xml",
  original_filename: "test.svg",
  ...
}
```

**Comment by dmitry-mukhin** [comment]
@nag5000 our CDN does not support image operations on SVG files just yet.
this is why the flag "is_image" is false.
we know this is a misleading name, too :(

**Comment by nag5000** [comment]
Then why are you closing this issue if the problem has to be solved?

**Comment by dmitry-mukhin** [comment]
@nag5000 technically,
1. this is not a problem
2. this is not widget's problem

we're aware of the interest in processing SVG files, and it's in our pipeline.
at the moment I can recommend to use a custom file validation feature if you need to accept images supported by Uploadcare image processing and some other formats (e.g. SVG).
