### ISSUE TITLE
Snyk - Prototype Pollution

### ISSUE THREAD

**Issue by timarney** [uploadcare/uploadcare-widget#535]
Hi 

I'm looking to submit a PR or at least flag this "security issue" that came up in a scan we did on on website.  Is this the correct repo - not seeing jQuery in your package.json 

https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006

<img width="867" alt="Screen Shot 2019-04-12 at 9 39 02 AM" src="https://user-images.githubusercontent.com/62242/56041572-09147280-5d07-11e9-9708-204085fd5e5f.png">

====

<img width="380" alt="Screen Shot 2019-04-12 at 9 39 33 AM" src="https://user-images.githubusercontent.com/62242/56041582-103b8080-5d07-11e9-8791-2d9d73b7231b.png">

**Comment by nd0ut** [comment]
Hi Tim! We're upgraded jquery to `v3.4.1` at widget `v3.7.3`. Thanks!

**Comment by jeetiss** [comment]
@markogresak we will fix this in next version, I'm currently working on it #551
