### ISSUE TITLE
Add `mimeType` to File Uploader Options for camera recording

### ISSUE THREAD

**Issue by weavermedia** [uploadcare/uploadcare-widget#542]
Different browsers support different mime types through the MediaRecorder object. If you add `mimeType` to the File Uploader options we could request a particular mime type from the browser for video recorded using MediaRecorder.

In Nov 2018 the mime type `video/webm` was hard-coded into the uploader widget then later changed to (I believe) accept the default mime type supplied by the browser.

https://github.com/uploadcare/uploadcare-widget/pull/516/files/d205b5bf3b071d7b9855f427cd03dbce70e7ab3f#diff-210dd7069c703b492ced317be0e77a42

Chrome used to deliver `video/webm` WebM files but now delivers `video/x-matroska` MKV files. It would be great if we could influence this with a `mimeType` setting.

**Comment by homm** [comment]
> then later changed to (I believe) accept the default mime type supplied by the browser.

Correct. As you mentioned, different browsers support different codecs and webm is not necessarily in this set. Also, the browser has more information about client resources and can choose suitable codec based on CPU power or the current load.

> Chrome used to deliver video/webm WebM files but now delivers video/x-matroska MKV files.

Webm in limited subset of Matroska container. Mime type was changed due to change in audio codec. Are you sure want to change this?

**Comment by weavermedia** [comment]
It is exactly the change in audio codec that has caused us issues with post-processing. After working successfully with the WebM files it suddenly reports 'Codec not supported in the container' for the Opus audio stream.

If the mime type was exposed as a option at least we would have a chance at getting a useable file. Have it accept the browser default if no mime type is supplied. And even fall back to the default if the supplied mime type is not available. Think of it more as a 'suggested' mime type.

It's easy for us to query MediaRecorder in advance to see if a particular mime type is supported.
