### ISSUE TITLE
Webcam video recording reports 1,000 frames per second

### ISSUE THREAD

**Issue by weavermedia** [uploadcare/uploadcare-widget#555]
Videos recorded in the widget using the webcam in Chrome have a frame rate of 1,000 fps.

This causes issues both with playback on iOS and future encoding of the video.

**Comment by jeetiss** [comment]
Hey @weavermedia, thanks for issue

We add frame rate constraint to video stream, now this should work fine

https://github.com/uploadcare/uploadcare-widget/blob/master/src/widget/tabs/camera-tab.js#L184
