### ISSUE TITLE
Improve DX for local development

### ISSUE THREAD

**Issue by jeetiss** [uploadcare/uploadcare-widget#581]
Setup rollup with watch mode and auto reloading for dummy pages and update development guide

**Comment by erin-doyle** [comment]
Agree.  I just spent longer than I should have getting set up to run a rails server to realize this isn't using a rails server for the dummy pages anymore...  Please do update the Development guide soon.

**Comment by erin-doyle** [comment]
I was going to try adding rollup watching and submit a PR but I can't get it to work.  I have tried just using an npm script set to "rollup -cw" as well as trying different options in the configuration file.  I've tried various includes options.  Nothing seems to make a difference.  The only thing it seems to notice has changed is if I change the config file.  It looks like in a much older version of rollup it had issues watching when the config returns an array (https://github.com/rollup/rollup/issues/2294#issuecomment-399275223).  This was supposedly fixed though so I'm not sure if it's still causing problems or there's something very specific that needs to be done in the config to make it work properly.

**Comment by jeetiss** [comment]
@erin-doyle thanks for info!
I made `npm run dev` script, can you help with testing it? In `dev-mode` branch

**Comment by erin-doyle** [comment]
@jeetiss awesome!  I looked at the PR and it looks good.  Yes, I can help with testing this later today. 👍

**Comment by erin-doyle** [comment]
I just tested this out.  It works great!  It is now recognizing when I make a change and is rebuilding and reloading the page with the changes!  Thanks for adding this!

**Comment by jeetiss** [comment]
@erin-doyle thanks for help ❤️
