### ISSUE TITLE
openDialog() fails with `settings is undefined` message in 3.8.1

### ISSUE THREAD

**Issue by illarionvk** [uploadcare/uploadcare-widget#669]
## Description

In 3.8.1 version, `openDialog()` fails with "jQuery.Deferred exception: settings is undefined" message after clicking 'Choose a local file' button.

The widget works correctly if I pin the CDN URL to v3.8.0.

### Steps to reproduce

1. Load the widget globally from CDN

    ```
    https://ucarecdn.com/libs/widget/3.8.1/uploadcare.full.min.js
    ```

1. Init widget manually (see attached screenshot)

1. Click 'Choose local file' button in the widget's modal window

### Expected result

The widget should present a file picker dialog and process the selected file

### Actual result

The widget shows an exception

### Environment

- widget version: 3.8.1
- `node -v`: n/a
- `npm -v`: n/a

Tested in latest Firefox and Chrome browsers.

### Screenshots

![error](https://user-images.githubusercontent.com/5012724/71819250-a086d600-308b-11ea-9bed-58d4bf00e55f.png)

![error-code-line](https://user-images.githubusercontent.com/5012724/71819265-aaa8d480-308b-11ea-9d52-c0ed0ed034a1.png)

![widget-init-code](https://user-images.githubusercontent.com/5012724/71819275-b1cfe280-308b-11ea-9796-87ada92bbee8.png)

**Comment by jeetiss** [comment]
Thanks for so detail issue.
We already fixed this issue, but it don't released yet.
As workaround you can use

```js
uploadcare.openDialog(null, '',  uploadcareSettings)
/// ... etc
```

and `openDialog` will work without issues

**Comment by ahhardin** [comment]
Is there an ETA for when this fix will be released?
