### ISSUE TITLE
Single file widget incorrectly uploads drag and dropped multiple files

### ISSUE THREAD

**Issue by jackc** [uploadcare/uploadcare-widget#739]
## Description

Dragging multiple files onto a dialog opened from a single file widget uploads all the files to Uploadcare but the application is only informed of one of them.

### Steps to reproduce

Drag multiple files onto the uploader dialog.

### Expected result

An error message telling the user to only upload a single file or at least only upload one of the files.

### Actual result

Multiple files are uploaded and all but one are "orphans" from the applications point of view.

### Environment

```
$ node -v
v12.14.0
$ npm -v
6.13.6
$ grep uploadcare package.json
    "uploadcare-widget": "^3.9.1"
```

**Comment by jeetiss** [comment]
@jackc thanks for issue
I'm going to fix that
