### ISSUE TITLE
Adding CSS via uploadcare.tabsCss.addStyle no longer works

### ISSUE THREAD

**Issue by henrymyers** [uploadcare/uploadcare-widget#777]
## Description
The third party tabs (e.g. Facebook, Instagram) now cause errors when trying to add CSS via `uploadcare.tabsCss.addStyle`.

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
```

Seems to be because the method used inside the iframes creates an **HTMLCollection** rather than a **Node**, and therefore can't be added via `document.body.appendChild`.

Here is the problematic code (minified):
```
    if (e.events.on("MessageFromParent", (function(e) {
        if ("embed-css" == e.type && e.url) {
            if (!/^https?:\/\//i.test(e.url))
                throw new Error("Embedded urls should be absolute. " + e.url);
            r.appendChild(Object(a.e)('<link rel="stylesheet" type="text/css" href="'.concat(i()(e.url), '" />')))
        }
        if ("embed-css" == e.type && e.style) {
            var t = Object(a.e)('<style type="text/css">');
            t.textContent = e.style,
            r.appendChild(t)
        }
    }
    )),
```
...which calls
```
    function(e) {
        var t = document.implementation.createHTMLDocument();
        return t.body.innerHTML = e,
        t.body.children
    }
```

### Steps to reproduce
Simply call `uploadcare.tabsCss.addStyle` and click on a 3rd party tab.

Can be tested on Codesandbox (uses the react-widget, but the error is coming from the facebook tab): 
https://codesandbox.io/s/uploadcarereact-widget-props-example-6e9uv

### Expected result
The specified CSS should be applied to the iframe successfully.

### Actual result
No CSS added.

### Environment

- widget version: 3.10.1
- `node -v`:
- `npm -v`:

**Comment by jeetiss** [comment]
@henrymyers thanks for such detailed issue description.
I'm going to fix that

**Comment by henrymyers** [comment]
Any news on this fix? I'd be happy to contribute, but don't see the 3rd party iframe code available anywhere.

**Comment by henrymyers** [comment]
Nevermind, I just emptied my cache again and it now works. Thanks!
