### ISSUE TITLE
Effects don't show up in multiple mode when importing english-only version

### ISSUE THREAD

**Issue by henrymyers** [uploadcare/uploadcare-widget#786]
## Description
When importing `uploadcare.lang.en.js` from uploadcare-widget, the effects tab no longer works with multiple file mode.

### Steps to reproduce
Dev Setup

1. Import `uploadcare.lang.en.js`
2. Import `uploadcare-widget-tab-effects`
3. Register the effects tab (`uploadcare.registerTab("preview", uploadcareTabEffects);`)
4. Set `data-multiple="true"`

User Steps

1. Click on the Uploadcare button
2. Upload multiple images
3. Click on any image in your list of uploads
4. Notice the missing effects

See CodeSandbox example for an immediate repro https://codesandbox.io/s/uploadcare-multiple-effects-en-only-6nuri

### Expected result
Just like with the default `uploadcare.js` file, the effects tab should appear when clicking on any image in your multiples list.

### Actual result
It only opens the cropper

### Environment
See the CodeSandbox example for a working repro setup.

- widget version: 3.10.2

**Comment by henrymyers** [comment]
@jeetiss I noticed this when working on the locale settings

**Comment by jeetiss** [comment]
yes 😞
this happen because `effects-tab` import and patch different widget bundle
https://github.com/uploadcare/uploadcare-widget-tab-effects/blob/a9308b7b4743a1c4fae5044397196710a056271b/src/index.js#L1

we need eng only version for `effects-tab` , i'm trying to do it on next week

**Comment by henrymyers** [comment]
Sounds good 👍  Anyway, I can just import the default bundle in the meantime. Just wanted to flag this.

**Comment by henrymyers** [comment]
@jeetiss Any news on an english-only version of the `uploadcare-tab-effects`?

**Comment by henrymyers** [comment]
Fixed by [PR 41](https://github.com/uploadcare/uploadcare-widget-tab-effects/pull/41)

**Comment by nd0ut** [comment]
@henrymyers Thank you so much for your help. It was released under `1.5.0` version
