### ISSUE TITLE
Crop Information Reduces the Image DPI to 72.

### ISSUE THREAD

**Issue by NicoleMGF** [uploadcare/uploadcare-widget#812]
Adding crop information to the uploadcare image_url reduces the image quality to 72 DPI.

## Description

Adding crop information to the uploadcare image_url reduces the image quality to 72 DPI.

### Steps to reproduce

Original image url: https://ucarecdn.com/a0bae15b-8f4b-4ee1-9744-52965d05663e/
Image has original 300 DPI.

Cropped image url: https://ucarecdn.com/a0bae15b-8f4b-4ee1-9744-52965d05663e/-/crop/3005x3840/center
Image has reduced quality at 72 DPI.

### Expected result
Expect the image size to be reduced not the image quality. There is no mention of DPI reduction in the crop documentation: https://uploadcare.com/docs/transformations/resize-crop/#operation-crop

### Actual result
Image quality is consistently reduced to 72 DPI.

### Environment

- widget version: 
- `node -v`:
- `npm -v`:

**Comment by optlsnd** [comment]
Hi @NicoleMGF, actually, it's not a bug of the uploader. When you add any image processing operation, the original EXIF metadata gets stripped, so you get the default DPI value on the output image. However, this doesn't affect the quality of the image. DPI has nothing to do with resolution when it comes to digital images where the resolution is measured in pixels. This [article](https://largeprinting.com/resources/image-resolution-and-dpi.html#:~:text=Print%20resolution%20is%20measured%20in,resolution%20for%20high%20resolution%20output.) explains this topic in more detail. So, when you print an image, you can set any DPI in your printing/editing software.
