### ISSUE TITLE
3.10.3 package - dependency not found

### ISSUE THREAD

**Issue by remirobichet** [uploadcare/uploadcare-widget#816]
## Description

Rebuild our app with new package version lead to "**This dependency was not found:  uploadcare-widget**" error.

It seems new package does not contains any files : 

![image](https://user-images.githubusercontent.com/15103630/110479397-a0e28d00-80e5-11eb-847f-b14737bccf12.png)

**Comment by nd0ut** [comment]
Relates to https://github.com/uploadcare/react-widget/issues/248

**Comment by nd0ut** [comment]
@remirobichet
Sorry about that ridiculous mistake, fixed it at 3.10.4!
