### ISSUE TITLE
UI issues with your widget

### ISSUE THREAD

**Issue by heymartinadams** [uploadcare/uploadcare-widget#853]
## Preview word
<img width="492" alt="CleanShot 2021-08-04 at 11 14 39@2x" src="https://user-images.githubusercontent.com/11673745/128233144-12c399d1-a0cb-41ce-b0e0-0691a9a08fd1.png">

The word “preview” needs to be adjusted to match the other tabs.

## “Crop and add this image”

<img width="312" alt="CleanShot 2021-08-04 at 11 17 58@2x" src="https://user-images.githubusercontent.com/11673745/128233513-875967f3-85c5-4063-9f55-62bb437eb740.png">

Redundant since people know what it does.

## Done

<img width="220" alt="CleanShot 2021-08-04 at 11 18 17@2x" src="https://user-images.githubusercontent.com/11673745/128233553-6754a068-e0a4-4eba-ada4-ece797a96e29.png">

Should say “submit” or “upload”.

## Crop icon

<img width="186" alt="CleanShot 2021-08-04 at 11 18 34@2x" src="https://user-images.githubusercontent.com/11673745/128233589-722391f0-3c34-463a-af7d-dea6e2280754.png">

Not needed.

## Powered by uploadcare

<img width="231" alt="CleanShot 2021-08-04 at 11 18 42@2x" src="https://user-images.githubusercontent.com/11673745/128233616-aa5f6d34-25a2-4660-8cfe-b48d75c6d1d8.png">

Can we remove this if we pay for the widget?

**Comment by optlsnd** [comment]
Hi @heymartinadams, thank you for the feedback! 

### Preview word

Normally, the tab looks like this
![image](https://user-images.githubusercontent.com/13101080/128344275-239d2f98-7061-4d4d-a673-ce5fbdb5edf7.png)

Probably, you've hidden the yellow circle with CSS (which also acts as a progress bar). Can you please check this?

### "Crop and add this image"

You can change the text if you find it redundant. It can be done by overriding locale items. See [Adding a Locale](https://uploadcare.com/docs/uploads/file-uploader/#add-locale) in our docs.

### Done

It can be changed via [UPLOADCARE_LOCALE_TRANSLATIONS](https://uploadcare.com/docs/uploads/file-uploader/#add-locale) as well.

### Crop icon

Can you elaborate on that, please? Do you mean there's no need to display the icon if there's only one crop option set?

### Powered by uploadcare

Yes, it can be removed with CSS

```css
.uploadcare--powered-by {
  display: none;
}
```

**Comment by heymartinadams** [comment]
Thank you, @optlsnd! 🎉 Everything you mentioned fully addressed our concerns. The locale information helped a lot — the widget is a lot more customizable than I believed it to be.
