### ISSUE TITLE
No DOM elements found matching selector in Svelte

### ISSUE THREAD

**Issue by hauselin** [uploadcare/uploadcare-widget#889]
## Summary

When using the widget with Svelte, I get this error: `No DOM elements found matching selector`. Svelte code is included below. I really appreciate any help anyone can provide. Thanks!

```js
<script>
	import uploadcare from "uploadcare-widget/uploadcare.lang.en.min.js";
	
	const widget = uploadcare.Widget("#uploader", {
		publicKey: "demopublickey",
		imagesOnly: true,
		crop: "300x200",
	});
</script>

<input id="uploader" type="hidden" />
```

## Relevant information

See Svelte REPL/example [here](https://svelte.dev/repl/b125071b234046b4b1e4805452761633?version=3.44.3).

### Environment (if relevant)

Svelte 3.44.3

**Comment by optlsnd** [comment]
Hi @hauselin, you can use `this` [binding](https://svelte.dev/docs#template-syntax-element-directives-bind-this) to get a reference to a rendered element. See https://svelte.dev/tutorial/bind-this. Here's how you can solve this:

```js
<script>
	import uploadcare from "uploadcare-widget/uploadcare.lang.en.min.js";
	import { onMount } from "svelte";
	
	let widgetInput, widget;
	
	onMount(() => {
		widget = uploadcare.Widget(widgetInput, {
			publicKey: "demopublickey",
			imagesOnly: true,
			crop: "300x200",
		});
		console.log(widget);
	});
</script>

<input id="uploader" type="hidden" bind:this={widgetInput} />
```

Hope this helps.

**Comment by hauselin** [comment]
Perfect! I've updated the code and it works. Thanks also for the reference to Svelte's `bind:this`. Thanks, @optlsnd!
