### ISSUE TITLE
Uploadcare Files as a source

### ISSUE THREAD

**Issue by alexrichardsweb** [uploadcare/uploadcare-widget#911]
Apologies if this is the wrong repo. Currently using the upload widget on a backend and was wondering if there is a way, or if there will be a way to enable access to Uploadcare files from within the widget? For example one of my clients uses the same image in a few places on their site and they have to re-upload it each time, which then adds a duplicate version of the same image to Uploadcare.

Thanks

**Comment by optlsnd** [comment]
Hi @alexrichardsweb, you may want to consider implementing a custom tab with upload history as described [here](https://uploadcare.com/docs/guides/files-browser/).
