### ISSUE TITLE
Cropping doesn't work with certain aspect ratios (like those with dots)

### ISSUE THREAD

**Issue by wub** [uploadcare/uploadcare-widget#920]
## Description

The widget doesn't work with various aspect ratios (such as those that contain a dot like 1.91:1) - it defaults to "FREE".

### Steps to reproduce

1. Go to https://codesandbox.io/s/agitated-pond-nezvwq?file=/src/index.js
2. Try to upload an image, and reach the crop step

### Expected result

In the demo, all aspect ratios should be represented.

### Actual result

Some aspect ratios fall back to "FREE".

### Environment

Chrome 104, macOS 12.1

- widget version: 3.18.0
- `node -v`: 16.17.0
- `npm -v`: 8.15.0

Thanks!

**Comment by nd0ut** [comment]
Hey @wub,

You can use `191:100` aspect ratio. But in this case the user will see `191:100` on the screen instead of `1.91:1`. Is that acceptable to you?

**Comment by wub** [comment]
Hey @nd0ut, thanks for your response. `191:100` is perfectly fine for our usecase, yes 😄 I'll close as wontfix but please feel free to reopen if needed.
