### ISSUE TITLE
Class name uploadcare--file-sources__item has only one underscore in the mobile all sources button

### ISSUE THREAD

**Issue by guillermodlpa** [uploadcare/uploadcare-widget#925]
## Description

When customizing the Uploadcare dialog on mobile, I noticed that the [...] button to show all sources has only one underscore `_` in one of its class names, while the other buttons have 2 underscores. See screenshot:

<img width="1264" alt="Screen Shot 2022-09-26 at 10 22 15" src="https://user-images.githubusercontent.com/1557348/192330205-8e187d9f-063a-46b2-bb0b-424f5ddda114.png">

I'm reporting this because it could be a typo in [tab-file.js](https://github.com/uploadcare/uploadcare-widget/blob/d94faa944a13185d541721f906a98c62c48a8b59/src/templates/tab-file.js#L47). Not sure if that difference was intentional.

I'd be happy to make a quick code contribution to the repository to add the missing underscore. Let me know :D

### Steps to reproduce

Load the widget and display it on a small screen.

### Expected result

Classes are the same, `uploadcare--file-sources__item`

### Actual result

Class for sources is `uploadcare--file-sources__item` but for only for the all button is `uploadcare--file-sources_item`

### Environment

- widget version:  3.18.0
- `node -v`: v16.14.2
- `npm -v`: 8.13.0

**Comment by nd0ut** [comment]
Hey @guillermodlpa,

Yeah, this is definitely a typo. Thank you!

**Comment by guillermodlpa** [comment]
Great, happy to have helped!
